<a href="https://colab.research.google.com/github/JairGF05/funcion_copy_numpy/blob/main/copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#A continuación se realiza un pequeño Slicing
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [4]:
#cambiar todos los valores del trrozo a cero
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [5]:
#Pero si volvemos al arreglo original, los datos ya se encuentran dañados
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [6]:
#copy nos permite crear un aocpia y hacer modficaciones sobre esta para evitar problemas como este
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [8]:
#Convierto todos los valosres d emi lista a 100
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
#revisamos el arreglo original para verificar que sus valores no se modificaron en este caso cambiar a 100
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])